title:              AKS Engineering Team Blog
email:              brian.redmond@microsoft.com
description:        Insights and best practices from the AKS Engineering Team
author:             Brian Redmond
baseurl:            "" # the subpath of your site, e.g. /blog
url:                "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:   theakscommunity
github_username:    Azure/aks


# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
